/**
 * Sources du registre scientifique V1. Vérification effectuée le 2026-09-27 :
 * - IDENTITÉ : recherche web (PMID, titre, auteurs, revue) ; `PARTIAL` dès qu'un élément manque ;
 * - CONTENU : `SEARCH_SUMMARY` pour toutes les sources. PubMed, Europe PMC et les sites des éditeurs étaient
 *   inaccessibles depuis l'environnement d'exécution (politique réseau) : ni résumé officiel ni texte
 *   intégral n'ont été lus. Les résultats ci-dessous sont limités à ce que les résumés consultés énonçaient ;
 *   aucune précision n'y est ajoutée. Chaque source reste à relire en texte intégral avant tout usage PRODUCTION.
 */
import type { ScienceSource } from './types.js';

const S = (s: Omit<ScienceSource, 'contentVerification'> & { contentVerification?: ScienceSource['contentVerification'] }): ScienceSource => ({ contentVerification: 'SEARCH_SUMMARY', ...s });

export const SCIENCE_SOURCES: readonly ScienceSource[] = [
  S({
    id: 'SRC.CURRIER_2026_ACSM', pmid: '41843416', year: '2026', evidenceType: 'position_stand',
    citation: 'Currier et al. ACSM Position Stand — Resistance Training Prescription for Muscle Function, Hypertrophy, and Physical Performance in Healthy Adults: An Overview of Reviews. Med Sci Sports Exerc. 2026;58(4):851–872.',
    population: 'Adultes en bonne santé (vue d’ensemble de 137 revues systématiques, plus de 30 000 participants)',
    outcomes: ['force musculaire', 'hypertrophie', 'performance physique'],
    findings: ['Vue d’ensemble des revues systématiques sur les variables de prescription de l’entraînement en résistance chez l’adulte en bonne santé (périmètre et taille selon le résumé consulté).'],
    identityVerification: 'CONFIRMED',
    limitations: 'Recommandations détaillées non extraites (résumé de recherche seulement) : la source sert de cadre général, jamais de justification d’une valeur numérique.',
  }),
  S({
    id: 'SRC.CURRIER_2023_NMA', pmid: '37414459', year: '2023', evidenceType: 'network_meta_analysis',
    citation: 'Currier BS, McLeod JC, Banfield L et al. [Prescription de l’entraînement en résistance : méta-analyse en réseau bayésienne]. Br J Sports Med. 2023.',
    population: 'Adultes en bonne santé',
    outcomes: ['force musculaire', 'hypertrophie'],
    findings: ['Méta-analyse en réseau bayésienne comparant des prescriptions d’entraînement en résistance (estimations détaillées non extraites).'],
    identityVerification: 'CONFIRMED',
    limitations: 'Estimations par prescription non extraites : non utilisée pour une valeur.',
  }),
  S({
    id: 'SRC.LOPEZ_2021', pmid: '33433148', doi: '10.1249/MSS.0000000000002585', year: '2021', evidenceType: 'network_meta_analysis',
    citation: 'Lopez P, Radaelli R, Taaffe DR et al. Resistance Training Load Effects on Muscle Hypertrophy and Strength Gain: Systematic Review and Network Meta-analysis. Med Sci Sports Exerc. 2021;53(6):1206–1216.',
    population: 'Adultes (28 études, 747 participants)',
    outcomes: ['hypertrophie', 'force (1RM)'],
    findings: ['Aucune différence d’hypertrophie entre charges faibles, modérées et élevées.', 'Gains de force supérieurs avec des charges élevées ou modérées qu’avec des charges faibles.'],
    identityVerification: 'CONFIRMED',
    limitations: 'Catégories de charge de la source non transposables en pourcentages exacts sans lecture intégrale.',
  }),
  S({
    id: 'SRC.ROBINSON_2024', pmid: '38970765', year: '2024', evidenceType: 'meta_analysis',
    citation: 'Robinson, Pelland, Remmert et al. [Proximité de l’échec, force et hypertrophie : série de méta-régressions]. Sports Med. 2024;54(9):2209–2231.',
    population: 'Adultes entraînés et non entraînés (méta-régressions)',
    outcomes: ['hypertrophie', 'force'],
    findings: ['L’hypertrophie augmente à mesure que les séries se rapprochent de l’échec.', 'Relation négligeable entre proximité de l’échec et gains de force.'],
    identityVerification: 'CONFIRMED',
    limitations: 'Proximité de l’échec ESTIMÉE (RIR non mesuré directement) ; pente non extraite.',
  }),
  S({
    id: 'SRC.REFALO_2023', pmid: '36334240', year: '2022/2023', evidenceType: 'meta_analysis',
    citation: 'Refalo, Helms, Trexler, Hamilton, Fyfe. [Proximité de l’échec et hypertrophie : revue systématique et méta-analyse]. 2022/2023 (revue non vérifiée).',
    population: 'Adultes (15 études)',
    outcomes: ['hypertrophie'],
    findings: ['L’entraînement jusqu’à l’échec n’est pas supérieur à l’arrêt avant l’échec pour l’hypertrophie (ES 0,12 ; p = 0,343).'],
    identityVerification: 'CONFIRMED',
    limitations: 'Hétérogénéité des définitions de l’échec ; population non détaillée ici.',
  }),
  S({
    id: 'SRC.PELLAND_2026', pmid: '41343037', year: '2026', evidenceType: 'meta_analysis',
    citation: 'Pelland, Remmert, Robinson, Hinson, Zourdos. [Volume hebdomadaire et fréquence : méta-régressions sur l’hypertrophie et la force]. Sports Med. 2026.',
    population: '67 études, 2 058 participants, 79,1 % d’hommes, âge moyen environ 25 ans',
    outcomes: ['hypertrophie', 'force'],
    findings: ['Relation dose–réponse du volume hebdomadaire avec rendements décroissants.', 'Fréquence : effet positif sur la force, négligeable sur l’hypertrophie.'],
    identityVerification: 'CONFIRMED',
    limitations: 'Population majoritairement masculine et jeune ; méthode de décompte des séries (fractionnaire ou non) non vérifiée.',
  }),
  S({
    id: 'SRC.SINGER_2024', pmid: '39205815', year: '2024', evidenceType: 'meta_analysis',
    citation: 'Singer et al. (dont Schoenfeld et Swinton). « Give it a rest » [durée du repos entre séries et hypertrophie : méta-analyse bayésienne]. Frontiers. 2024.',
    population: '9 études',
    outcomes: ['hypertrophie'],
    findings: ['Chevauchement important des effets entre durées de repos ; hétérogénéité.'],
    identityVerification: 'PARTIAL',
    limitations: 'Liste complète des auteurs et titre exact non vérifiés ; faible nombre d’études ; hypertrophie seulement.',
  }),
  S({
    id: 'SRC.GRGIC_2018', pmid: '28933024', year: '2018', evidenceType: 'systematic_review',
    citation: 'Grgic et al. [Durée du repos entre séries et force : revue systématique]. Sports Med. 2018;48(1):137–151.',
    population: '23 études, 491 participants',
    outcomes: ['force musculaire'],
    findings: ['Revue systématique de l’effet de la durée du repos entre séries sur la force (sens et ampleur à confirmer en texte intégral).'],
    identityVerification: 'CONFIRMED',
    limitations: 'Conclusions détaillées non extraites : aucune durée précise n’en est tirée.',
  }),
  S({
    id: 'SRC.HALPERIN_2022', pmid: '34542869', year: '2022', evidenceType: 'scoping_review',
    citation: 'Halperin et al. [Précision de la prédiction des répétitions jusqu’à l’échec : revue exploratoire et méta-analyse]. 2022 (revue non vérifiée).',
    population: '12 études, 414 participants',
    outcomes: ['précision de la prédiction des répétitions jusqu’à l’échec'],
    findings: ['Sous-estimation moyenne d’environ 0,95 répétition du nombre de répétitions possibles.'],
    identityVerification: 'PARTIAL',
    limitations: 'Revue exploratoire ; liste complète des auteurs non vérifiée ; facteurs modérateurs non extraits.',
  }),
  S({
    id: 'SRC.HUGHES_2020', pmid: '33337690', year: '2020', evidenceType: 'experimental_study',
    citation: 'Hughes, Peiffer, Scott. [Estimation du RIR sur quatre exercices]. J Strength Cond Res. 2020.',
    population: '21 hommes entraînés',
    outcomes: ['précision de l’estimation du RIR (65, 75 et 85 % 1RM)'],
    findings: ['Étude de la précision de l’estimation du RIR sur quatre exercices à trois intensités (résultats chiffrés non extraits).'],
    identityVerification: 'CONFIRMED',
    limitations: 'Petit échantillon masculin entraîné ; étude unique ; résultats non extraits.',
  }),
  S({
    id: 'SRC.WILSON_2012', pmid: '22002517', year: '2012', evidenceType: 'meta_analysis',
    citation: 'Wilson et al. [Entraînement concurrent : méta-analyse de l’interférence]. J Strength Cond Res. 2012;26(8):2293–2307.',
    population: '21 études',
    outcomes: ['force', 'hypertrophie', 'puissance'],
    findings: ['L’interférence dépend de la modalité d’endurance, de sa fréquence et de sa durée.'],
    identityVerification: 'CONFIRMED',
    limitations: 'Méta-analyse ancienne ; aucune fenêtre temporelle chiffrée n’en est tirée.',
  }),
  S({
    id: 'SRC.LUNDBERG_2022', pmid: '35476184', year: '2022', evidenceType: 'meta_analysis',
    citation: 'Lundberg, Feuerbacher, Sünkeler, Schumann. [Entraînement concurrent et hypertrophie des fibres : revue systématique et méta-analyse]. Sports Med. 2022.',
    population: 'Adultes (revue systématique et méta-analyse)',
    outcomes: ['hypertrophie des fibres musculaires'],
    findings: ['Atténuation faible de l’hypertrophie des fibres par l’entraînement concurrent.', 'Atténuation plus marquée avec la course qu’avec le vélo, au moins pour les fibres de type I.'],
    identityVerification: 'CONFIRMED',
    limitations: 'Hypertrophie des fibres seulement ; ampleur non extraite.',
  }),
  S({
    id: 'SRC.CHEN_2024', pmid: '38187085', year: '2024', evidenceType: 'network_meta_analysis',
    citation: 'Chen, Feng, Huang, Wang, Mi. [Types d’entraînement concurrent, force des membres inférieurs et section musculaire : méta-analyse en réseau]. J Exerc Sci Fit. 2024.',
    population: '40 études, 841 participants',
    outcomes: ['force des membres inférieurs', 'surface de section musculaire'],
    findings: ['Méta-analyse en réseau des types d’entraînement concurrent (classements non extraits).'],
    identityVerification: 'PARTIAL',
    limitations: 'Titre exact et résultats non vérifiés ; non utilisée pour une valeur.',
  }),
  S({
    id: 'SRC.KASSIANO_2022', pmid: '35438660', year: '2022', evidenceType: 'systematic_review',
    citation: 'Kassiano et al. [Variation des exercices, hypertrophie et force : revue systématique]. J Strength Cond Res. 2022.',
    population: '8 études, 241 jeunes hommes',
    outcomes: ['hypertrophie', 'force'],
    findings: ['Une variation systématique des exercices peut être bénéfique.', 'Une variation excessive et aléatoire peut compromettre les gains.'],
    identityVerification: 'PARTIAL',
    limitations: 'Liste complète des auteurs non vérifiée ; petit corpus de jeunes hommes.',
  }),
  S({
    id: 'SRC.GRGIC_2020', pmid: '32681399', year: '2020', evidenceType: 'systematic_review',
    citation: 'Grgic, Lazinica, Schoenfeld, Pedisic. [Fiabilité test–retest du 1RM : revue systématique]. 2020 (revue non vérifiée).',
    population: '32 études',
    outcomes: ['fiabilité test–retest du 1RM'],
    findings: ['ICC médian 0,97 ; coefficient de variation médian 4,2 %.'],
    identityVerification: 'CONFIRMED',
    limitations: 'Fiabilité d’un 1RM MESURÉ, pas d’un e1RM estimé par formule.',
  }),
  S({
    id: 'SRC.HICKMOTT_2022', pmid: '35038063', year: '2022', evidenceType: 'meta_analysis',
    citation: 'Hickmott, Chilibeck, Shaw, Butcher. [Autorégulation de la charge et du volume : revue systématique et méta-analyse]. Sports Med Open. 2022.',
    population: 'Adultes (revue systématique et méta-analyse)',
    outcomes: ['force', 'hypertrophie'],
    findings: ['Revue de l’autorégulation de la charge et du volume (estimations non extraites).'],
    identityVerification: 'CONFIRMED',
    limitations: 'Résultats non extraits : cadre seulement.',
  }),
  S({
    id: 'SRC.AUTOREG_NMA_2025', pmid: '40791980', year: '2025', evidenceType: 'network_meta_analysis',
    citation: 'Autoregulated resistance training for maximal strength: systematic review and network meta-analysis (2025) — auteurs et revue non vérifiés.',
    population: 'Adultes (méta-analyse en réseau)',
    outcomes: ['force maximale'],
    findings: ['APRE, RPE et entraînement basé sur la vitesse plus efficaces que la prescription en pourcentage (SUCRA APRE 93 %).'],
    identityVerification: 'PARTIAL',
    limitations: 'Auteurs et revue non vérifiés ; classement SUCRA ≠ taille d’effet.',
  }),
  S({
    id: 'SRC.MOESGAARD_2022', pmid: '35044672', year: '2022', evidenceType: 'meta_analysis',
    citation: 'Moesgaard, Beck, Christiansen, Aagaard, Lundbye-Jensen. [Périodisation à volume égal, force et hypertrophie : revue systématique et méta-analyse]. 2022 (revue non vérifiée).',
    population: 'Adultes (programmes à volume égal)',
    outcomes: ['force (1RM)', 'hypertrophie'],
    findings: ['Programmes périodisés supérieurs aux non périodisés pour le 1RM.', 'Ondulatoire supérieur au linéaire seulement chez les entraînés.', 'Aucune différence d’hypertrophie.'],
    identityVerification: 'CONFIRMED',
    limitations: 'Aucune durée de cycle ni fraction de progression n’en est tirée.',
  }),
  S({
    id: 'SRC.FRADKIN_2010', pmid: '19996770', year: '2010', evidenceType: 'meta_analysis',
    citation: 'Fradkin, Zazryn, Smoliga. [Échauffement et performance physique : revue systématique et méta-analyse]. J Strength Cond Res. 2010;24(1):140–148.',
    population: 'Études sur l’échauffement et la performance physique',
    outcomes: ['performance physique'],
    findings: ['Revue systématique et méta-analyse de l’effet de l’échauffement sur la performance (résultats chiffrés non extraits).'],
    identityVerification: 'CONFIRMED',
    limitations: 'Résultats non extraits ; aucune durée d’échauffement n’en est tirée.',
  }),
  S({
    id: 'SRC.WARMUP_FORCE_MA', pmid: '39864808', year: '2025', evidenceType: 'meta_analysis',
    citation: 'The effect of muscle warm-up on voluntary and evoked force-time parameters: a systematic review and meta-analysis with meta-regression — auteurs et revue non vérifiés.',
    population: 'Études d’échauffement musculaire (paramètres force–temps)',
    outcomes: ['taux de développement de la force', 'puissance', 'force maximale'],
    findings: ['Amélioration du taux de développement de la force et de la puissance, pas de la force maximale.', 'Échauffement actif non supérieur au passif.'],
    identityVerification: 'PARTIAL',
    limitations: 'Auteurs, revue et année exacte non vérifiés.',
  }),
  S({
    id: 'SRC.WARMUP_HIGHLOAD', pmid: '39593476', year: 'non vérifiée', evidenceType: 'experimental_study',
    citation: 'Titre commençant par « High-load and low-volume warm-up increases… » — auteurs, revue et contenu non vérifiés.',
    population: 'Non vérifiée',
    outcomes: ['non vérifiés'],
    findings: [],
    identityVerification: 'PARTIAL',
    limitations: 'Identité partielle, contenu inconnu : AUCUNE revendication ne s’appuie sur cette source.',
  }),
];
